/* =====================================================================
   PLAN DATA — the single place to edit when the study plan changes.
   Keep in sync with the notes in ../ (see CLAUDE.md sync rule).
   These globals are consumed by app.js:
     TYPE, it(), WEEKS, BLOCKS, PROJECTS, REPROS, POSTS, CPS
   ===================================================================== */
"use strict";

// ---------- data ----------
var TYPE={book:"CH",repro:"REPRO",proj:"PROJ",cert:"CERT",post:"POST",task:"DO"};
function it(t,x){return {t:t,x:x};}
var WEEKS=[
 {id:1,blk:"A",start:"2026-07-18",dates:"Jul 18–24",title:"Foundations & ignition",
  core:[it("book","Finish Ch 10 loose ends — Optuna, save/load, torch.compile (labs 10–12)"),
        it("task","Make the repo production-minded: pinned deps, src/ layout, Makefile, README"),
        it("post","Rewrite LinkedIn as a landing page (sound like a person) + ship post #1 (a metrics gotcha from finishing Ch 10)"),
        it("cert","Pick SAA resources; take a diagnostic Tutorials Dojo timed test")],
  stretch:["Skim Ch 9 (Scikit-Learn MLP) as a 30-min bridge to PyTorch"],
  del:"Repo restructured + profile live + SAA baseline score"},
 {id:2,blk:"A",start:"2026-07-25",dates:"Jul 25–31",title:"SAA: Secure Architectures (30%)",
  core:[it("cert","SAA Domain 1 — IAM, KMS, encryption, security groups, VPC security (the biggest domain)"),
        it("book","Ch 7 (Dimensionality Reduction) light — PCA intuition + one hands-on notebook")],
  stretch:["TD cheat-sheet pass on VPC/networking"],
  del:"Domain-1 practice set ≥ 70%"},
 {id:3,blk:"A",start:"2026-08-01",dates:"Aug 1–7",title:"SAA: Resilient + High-Performing (26%+24%)",
  core:[it("cert","SAA Domains 2–3 — multi-AZ, ELB/ASG, RDS/Aurora, S3 tiers, caching, SQS/SNS"),
        it("book","Ch 8 (Unsupervised) light — k-means + DBSCAN + GMM for anomaly detection")],
  stretch:["post #2 — “I compressed a photo with linear algebra and watched it fall apart one dimension at a time” (PCA)"],
  del:"Domains 2–3 practice set ≥ 70%"},
 {id:4,blk:"A",start:"2026-08-08",dates:"Aug 8–14",title:"SAA: Cost + weak-area drilling",
  core:[it("cert","SAA Domain 4 (cost) + re-drill weakest domain; start full-length TD exams"),
        it("proj","Start P0 — anomaly/clustering demo on a real-ish dataset (uses Ch 8)")],
  stretch:[],
  del:"First full TD exam done + reviewed (expect ~65–75%)"},
 {id:5,blk:"A",start:"2026-08-15",dates:"Aug 15–21",title:"SAA: exam-ready",
  core:[it("cert","TD full exams until ≥ 80% on fresh sets (go/no-go); review every wrong answer"),
        it("proj","Finish + deploy P0 (Streamlit / HF Space)")],
  stretch:[],
  del:"≥ 80% fresh TD + P0 live URL"},
 {id:6,blk:"A",start:"2026-08-22",dates:"Aug 22–28",title:"Sit SAA + reset",
  core:[it("cert","Sit AWS SAA-C03 (book it Tue–Thu)"),
        it("post","post #3 — “The handful of AWS ideas that actually changed how I'd deploy a model”"),
        it("proj","Write P0 case study; pin it"),
        it("book","Begin Ch 11 reading")],
  stretch:[],
  del:"SAA passed 🎉 · P0 case study published"},
 {id:7,blk:"B",start:"2026-08-29",dates:"Aug 29–Sep 4",title:"Ch 11 (Training DNNs) + makemore",
  core:[it("book","Ch 11 core labs: init, activations, BatchNorm/LayerNorm, optimizers, LR schedules, dropout"),
        it("repro","Start makemore — char-level LM from scratch (Karpathy)")],
  stretch:["Ch 11 gradient-clipping + max-norm labs"],
  del:"Reusable train()/build_mlp() helper + makemore bigram/MLP stages working"},
 {id:8,blk:"B",start:"2026-09-05",dates:"Sep 5–11",title:"Finish Ch 11 + makemore",
  core:[it("book","Wrap Ch 11 — assemble the “default recipe” pipeline"),
        it("repro","Finish makemore (through the MLP/WaveNet stage)"),
        it("post","post #4 — “I taught a tiny neural net to invent names — watching gibberish become almost-real words was unreasonably fun”")],
  stretch:[],
  del:"makemore repo + annotated README (mini paper→code writeup)"},
 {id:9,blk:"B",start:"2026-09-12",dates:"Sep 12–18",title:"Ch 12 (CNNs) + ⚠ CERT DECISION",
  core:[it("book","Ch 12 core: conv/pool, standard recipe, transfer learning, a ResNet block"),
        it("proj","Start P1 — transfer-learning image classifier (fine-grained, pretrained backbone)"),
        it("cert","CERT DECISION — race MLA-C01 (sit by Sep 26) or target MLA-C02? Default: C02")],
  stretch:[],
  del:"Cert decision made & written down · P1 training working"},
 {id:10,blk:"B",start:"2026-09-19",dates:"Sep 19–25",title:"Finish Ch 12 + deploy P1",
  core:[it("book","Finish Ch 12"),
        it("proj","Deploy P1 to HF Space (Gradio) + eval report: per-class acc, confusion matrix, failure cases"),
        it("post","post #5 — P1 (“a frozen pretrained model embarrassed my from-scratch one — then I hunted for where it still breaks”)")],
  stretch:[],
  note:"If racing MLA-C01: this + next week go cert-heavy; sit by Sep 26.",
  del:"P1 live URL + case study"},
 {id:11,blk:"B",start:"2026-09-26",dates:"Sep 26–Oct 2",title:"Ch 13 (Sequences / time-series)",
  core:[it("book","Ch 13 core: RNN/LSTM, forecasting, windowing/data-prep, ARMA baseline"),
        it("proj","Start P2 — forecasting / predictive-maintenance (classic-ML hedge; XGBoost vs LSTM)")],
  stretch:["Multivariate / multi-step forecasting lab"],
  del:"P2 baseline + LSTM comparison notebook"},
 {id:12,blk:"B",start:"2026-10-03",dates:"Oct 3–9",title:"Deploy P2 (the hedge project)",
  core:[it("proj","Deploy P2 as a small FastAPI service + metrics writeup (MAE/RMSE vs baseline)"),
        it("post","post #6 — “I was sure the LSTM would win. The boring gradient-boosted trees won, and it wasn't close”")],
  stretch:[],
  del:"P2 live + case study — Block B done: 3 deployed things + 1 reproduction"},
 {id:13,blk:"C",start:"2026-10-10",dates:"Oct 10–16",title:"Ch 14 (NLP + attention) + nanoGPT start",
  core:[it("book","Ch 14 core: embeddings, char-RNN, the attention mechanism, HF tokenizers"),
        it("repro","Start nanoGPT / build-nanogpt (reproduce a GPT-2-class model, scaled to your hardware)")],
  stretch:[],
  del:"Attention understood cold + nanoGPT training loop running"},
 {id:14,blk:"C",start:"2026-10-17",dates:"Oct 17–23",title:"Ch 15 (Transformers) deep + nanoGPT",
  core:[it("book","Ch 15 pt 1 — positional encoding, multi-head attention, build an encoder-decoder"),
        it("repro","nanoGPT continues")],
  stretch:[],
  del:"You can draw the Transformer block from memory · nanoGPT generating text"},
 {id:15,blk:"C",start:"2026-10-24",dates:"Oct 24–30",title:"Finish nanoGPT + start P3",
  core:[it("repro","Finish nanoGPT; write the paper→code annotated writeup"),
        it("post","post #7 — “I rebuilt GPT-2 from scratch just to understand attention — the idea underneath is almost embarrassingly simple”"),
        it("proj","Start P3 — domain-specific RAG API (anchor): pick a niche corpus")],
  stretch:[],
  del:"nanoGPT writeup published + P3 ingestion/chunking pipeline"},
 {id:16,blk:"C",start:"2026-10-31",dates:"Oct 31–Nov 6",title:"Ch 15 (LLMs) + P3 build",
  core:[it("book","Ch 15 pt 2 — encoder/decoder-only, SFT/RLHF/DPO, chatbots, MCP (grasp concepts)"),
        it("proj","P3 core: vector DB + retrieval + reranking + a generation endpoint")],
  stretch:[],
  del:"P3 answers questions end-to-end (rough)"},
 {id:17,blk:"C",start:"2026-11-07",dates:"Nov 7–13",title:"Finish + deploy P3 (anchor)",
  core:[it("proj","Add RAGAS eval, wrap in FastAPI + Docker, deploy. Quantify faithfulness, relevancy, hit-rate, latency/cost"),
        it("post","post #8 — P3 (“my RAG demo answered everything confidently — then I checked how many answers the docs actually supported”)")],
  stretch:[],
  del:"P3 live URL + eval dashboard + case study — your flagship"},
 {id:18,blk:"C",start:"2026-11-14",dates:"Nov 14–20",title:"Appendix B (quantization) + LoRA",
  core:[it("book","Appendix B — mixed precision, quantization, QAT/PTQ (feeds the inference/MLOps wedge)"),
        it("repro","LoRA/QLoRA fine-tune reproduction (from-scratch adapter → PEFT; free Colab T4)"),
        it("proj","Start P4 — LLM eval & observability pipeline over P3")],
  stretch:[],
  del:"A fine-tuned adapter + P4 tracing scaffold"},
 {id:19,blk:"C",start:"2026-11-21",dates:"Nov 21–27",title:"P4 (your wedge) build",
  core:[it("proj","P4: RAGAS/DeepEval suite + LangSmith/Phoenix tracing + golden-dataset regression + an “LLM CI” GitHub Action that fails the build if faithfulness drops"),
        it("post","post #9 — “The least glamorous question in LLM apps, and the one I can't stop thinking about: how do you know the output is right?” ← signature post")],
  stretch:[],
  del:"P4 running as a CI gate on P3"},
 {id:20,blk:"D",start:"2026-11-28",dates:"Nov 28–Dec 4",title:"Ch 16 + Ch 17 + finish P4",
  core:[it("book","Ch 16 (ViT + CLIP) + Ch 17 (speeding up Transformers / inference optimization)"),
        it("proj","Finish + polish P4; publish its case study")],
  stretch:["A tiny CLIP zero-shot demo"],
  del:"P4 case study live"},
 {id:21,blk:"D",start:"2026-12-05",dates:"Dec 5–11",title:"P5 (agentic OR MLOps)",
  core:[it("proj","P5 — pick one: (a) LangGraph agent w/ evals + cost/latency guardrails, or (b) MLOps service (Docker+CI+drift monitoring+alerting). Deploy it."),
        it("post","post #10 — P5 (“I gave a model some tools and let it loose — it confidently did the wrong thing, so I spent a week on guardrails”)")],
  stretch:[],
  del:"P5 live + case study"},
 {id:22,blk:"D",start:"2026-12-12",dates:"Dec 12–18",title:"Ch 18/19 (light) + buffer",
  core:[it("book","Ch 18 (autoencoders/GANs/diffusion — concepts + optional tiny DDPM) light; Ch 19 (RL) skim only")],
  stretch:["A small diffusion sample grid → post #11 (“I watched a model turn pure static into a picture, step by step. Still feels like magic”)"],
  del:"Caught up; DL arc conceptually complete (this week absorbs slippage)"},
 {id:23,blk:"D",start:"2026-12-19",dates:"Dec 19–25",title:"Consolidate the portfolio",
  core:[it("task","Pin the 3 anchors (P3, P4, best of P1/P5); overhaul each README to Problem→Approach→Result→Impact with numbers"),
        it("task","Build/polish a one-page portfolio site (GitHub Pages) linking demos, repros, posts"),
        it("repro","Publish the LoRA writeup if not already")],
  stretch:[],
  del:"3 pinned, deployed, quantified projects + portfolio site"},
 {id:24,blk:"D",start:"2026-12-26",dates:"Dec 26–30",title:"Position for 2027",
  core:[it("task","Create Braintrust + a niched Upwork profile; write 3–5 quantified case studies into them"),
        it("post","post #12 — “Six months, a lot of broken training runs, and a few things I'm proud of — what building in public taught me” (freelance line kept quiet)"),
        it("task","Draft the MLA-C02 Q1-2027 prep plan + a freelance-launch checklist")],
  stretch:[],
  del:"Freelance profiles live · retrospective posted · 2027 runway set"}
];
var BLOCKS=[
 {id:"A",title:"Setup + SAA cert + Part I finish",meta:"W0–5 · Jul 18 – Aug 28"},
 {id:"B",title:"Core DL + first projects + cert decision",meta:"W6–11 · Aug 29 – Oct 9"},
 {id:"C",title:"Transformers / LLMs + anchor projects",meta:"W12–18 · Oct 10 – Nov 27"},
 {id:"D",title:"Agentic / MLOps + consolidate + position",meta:"W19–23 · Nov 28 – Dec 30"}
];
var PROJECTS=[
 {id:"P0",name:"Anomaly / clustering demo",tag:"classic-ML · easy win",feeds:"Ch 7,8 · W3–5",
  body:"Find natural segments + flag anomalies on an unlabeled real-ish dataset. PCA/UMAP → k-means/DBSCAN → GMM/IsolationForest → Streamlit upload app.",
  metrics:"silhouette · precision/recall of flags on a labeled subset"},
 {id:"P1",name:"Transfer-learning image classifier",tag:"CV · deployed",feeds:"Ch 12 · W8–9",
  body:"Fine-grained task, few images/class. Pretrained backbone → freeze → head → differential-LR fine-tune. Gradio: image → top-3.",
  metrics:"acc vs from-scratch · per-class · confusion matrix · 3–5 honest failures"},
 {id:"P2",name:"Forecasting / predictive maintenance",tag:"the classic-ML hedge",feeds:"Ch 13 · W10–11",
  body:"Predict something a manager would pay to know. Windowed features → XGBoost baseline → LSTM → honest backtest → FastAPI /predict.",
  metrics:"MAE/RMSE vs naive baseline · a cost/impact framing"},
 {id:"P3",name:"Domain-specific RAG API",tag:"the 2026 golden project",feeds:"Ch 14,15 · W14–16",anchor:true,
  body:"Accurate, cited Q&A over a niche corpus. Smart chunking → vector DB → hybrid dense+BM25 → cross-encoder rerank → grounded generation → FastAPI + Docker.",
  metrics:"RAGAS faithfulness/relevancy · hit-rate@k · p50/p95 latency · cost/query · before/after reranking"},
 {id:"P4",name:"LLM eval & observability pipeline",tag:"your signature",feeds:"Ch 15 · App B · W17–19",anchor:true,
  body:"The layer that catches quality drops before users do. Golden dataset → RAGAS+DeepEval + LLM-judge → tracing → an “LLM CI” Action that fails the build below thresholds.",
  metrics:"catches an injected regression · % hallucinations caught · eval-run latency"},
 {id:"P5",name:"Agentic workflow OR MLOps service",tag:"rounds out the story",feeds:"Ch 17 · App B · W20",
  body:"(a) LangGraph tool-using agent with self-correction + guardrails, or (b) a model behind Docker+CI+drift monitoring+alerting. Recommendation: (a) for the wow.",
  metrics:"task success · tool-call accuracy · cost/task · guardrail catches"}
];
var REPROS=[
 {id:"makemore",name:"makemore",tag:"~8–15 h · W6–7",body:"Char-level LM from scratch. On-ramp to autograd/backprop/embeddings. Optional if time-pressed — nanoGPT subsumes it."},
 {id:"nanogpt",name:"nanoGPT / build-nanogpt",tag:"⭐ ~15–30 h · W12–14",body:"Reproduce a GPT-2-class model in a few hundred lines. Highest-signal reproduction."},
 {id:"lora",name:"LoRA / QLoRA fine-tune",tag:"⭐ ~10–20 h · W17",body:"From-scratch adapter → the PEFT production path; QLoRA runs on a free Colab T4. Most directly hireable."}
];
var POSTS=[
 {n:1,w:"W0",t:"A small bug that made my model look worse than it was — and what it taught me about trusting metrics"},
 {n:2,w:"W2",t:"I compressed a photo with nothing but linear algebra, then watched it fall apart one dimension at a time"},
 {n:3,w:"W5",t:"The handful of AWS ideas that actually changed how I'd deploy a model"},
 {n:4,w:"W7",t:"I taught a tiny neural net to invent names — watching gibberish become almost-real words was unreasonably fun"},
 {n:5,w:"W9",t:"A frozen pretrained model embarrassed my from-scratch one — then I went hunting for where it still breaks"},
 {n:6,w:"W11",t:"I was sure the LSTM would win. The boring gradient-boosted trees won, and it wasn't close"},
 {n:7,w:"W14",t:"I rebuilt GPT-2 from scratch just to understand attention — the idea underneath is almost embarrassingly simple"},
 {n:8,w:"W16",t:"My RAG demo answered everything confidently. Then I checked how many answers the documents actually supported"},
 {n:9,w:"W18",t:"⭐ The least glamorous question in LLM apps, and the one I can't stop thinking about: how do you know the output is right?"},
 {n:10,w:"W20",t:"I gave a model some tools and let it loose. It confidently did the wrong thing — so I spent a week on guardrails"},
 {n:11,w:"W21",t:"(stretch) I watched a model turn pure static into a picture, step by step. Still feels like magic"},
 {n:12,w:"W23",t:"Six months, a lot of broken training runs, and a few things I'm genuinely proud of — what building in public taught me"}
];
var CPS=[
 {n:1,when:"End of Block A · ~W5",title:"Does the machine run?",q:"Pure execution test — no market signal expected yet.",big:false},
 {n:2,when:"End of Block B · ~W11",title:"Can I ship, and is anyone noticing?",q:"Execution proven + first weak pulse. Cert decision must be locked.",big:false},
 {n:3,when:"End of Block C · ~W18",title:"Do the anchors exist? — THE BIG ONE",q:"P3 + P4 are the proof you can build & prove production LLM systems.",big:true},
 {n:4,when:"End of Block D · ~W23",title:"Am I positioned to sell?",q:"Positioning + first real read. Paid work by Dec 30 is a bonus, not the bar.",big:false},
 {n:5,when:"~Q2 2027",title:"Does the market pay? — the real thesis test",q:"Only here do you judge the strategy — after a genuine 8–12 wk outreach push.",big:false}
];
